export const cognomi = [
    'Barella',
    'Bianchi',
    'Berlusconi',
    'Brachetta',
    'Bruno',
    'Centofanti',
    'Colantuono',
    'Colombo',
    'Conte',
    'Conti',
    'Costa',
    'Cuccuru',
    'De Luca',
    'Di Iorio',
    'Esposito',
    'Ferrari',
    'Fusco',
    'Gallo',
    'Giordano',
    'Giotto',
    'Greco',
    'Lombardi',
    'Mancini',
    'Magalli',
    'Marino',
    'Meloni',
    'Messina',
    'Moretti',
    'Prodi',
    'Ricci',
    'Rizzo',
    'Romano',
    'Rossi',
    'Russo',
    'Scariolo',
];