export const nomi = [
    // Maschi
    { nome: 'Achille', sesso: 'M' },
    { nome: 'Alessandro', sesso: 'M' },
    { nome: 'Andrea', sesso: 'M' },
    { nome: 'Daniele', sesso: 'M' },
    { nome: 'Francesco', sesso: 'M' },
    { nome: 'Gabriele', sesso: 'M' },
    { nome: 'Giorgio', sesso: 'M' },
    { nome: 'Leonardo', sesso: 'M' },
    { nome: 'Lorenzo', sesso: 'M' },
    { nome: 'Luca', sesso: 'M' },
    { nome: 'Mattia', sesso: 'M' },
    { nome: 'Simone', sesso: 'M' },
    { nome: 'Stefano', sesso: 'M' },
    { nome: 'Tommaso', sesso: 'M' },
    // Femmine
    { nome: 'Alice', sesso: 'F' },
    { nome: 'Angela', sesso: 'F' },
    { nome: 'Anna', sesso: 'F' },
    { nome: 'Aurora', sesso: 'F' },
    { nome: 'Carla', sesso: 'F' },
    { nome: 'Emma', sesso: 'F' },
    { nome: 'Ginevra', sesso: 'F' },
    { nome: 'Giorgia', sesso: 'F' },
    { nome: 'Giulia', sesso: 'F' },
    { nome: 'Greta', sesso: 'F' },
    { nome: 'Irma', sesso: 'F' },
    { nome: 'Ivana', sesso: 'F' },
    { nome: 'Marika', sesso: 'F' },
    { nome: 'Roberta', sesso: 'F' },
    { nome: 'Sofia', sesso: 'F' },
    { nome: 'Valentina', sesso: 'F' },
];